name: Cron

on:
  schedule:
    # Run every day at 00:00 UTC
    - cron: 0 0 * * *

jobs:
  main:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
          - Windows
          - MacOS
        python-version:
          - "3.10"
          - 3.9
          - 3.8
    env:
      PY_COLORS: 1
      TOXENV: piplatest-coverage
      TOX_PARALLEL_NO_SPINNER: 1
    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: >-
            ${{
              runner.os == 'Linux' &&
              '~/.cache/pip'
              || ''
            }}${{
              runner.os == 'macOS' &&
              '~/Library/Caches/pip'
              || ''
            }}${{
              runner.os == 'Windows' &&
              '~\AppData\Local\pip\Cache'
              || ''
            }}
          key: >-
            ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}-${{
            hashFiles('setup.py') }}-${{ hashFiles('tox.ini') }}-${{
            hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install test dependencies
        run: python -m pip install -U tox virtualenv
      - name: Prepare test environment
        run: tox --notest -p auto --parallel-live
      - name: Test python-wiremock
        run: tox
